name: "setup php"
description: "Setup PHP"

inputs:
  php-version:
    description: "PHP version to be used"
    required: true
  php-extensions:
    description: "PHP extensions to be used"
    default: mbstring, intl, gd, imagick, zip, dom, pdo_mysql, pdo_pgsql, fileinfo
    required: false
  cache-key:
    default: cachev1
    description: "Custom extension cache key"
    required: false

runs:
  using: "composite"
  steps:
    - name: setup php extensions cache
      id: extensions-cache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: ${{ inputs.cache-key }}

    - name: cache php extensions
      uses: actions/cache@v3
      with:
        path: ${{ steps.extensions-cache.outputs.dir }}
        key: ${{ steps.extensions-cache.outputs.key }}
        restore-keys: ${{ steps.extensions-cache.outputs.key }}
        
    - name: setup php ${{ inputs.php-version }}
      uses: shivammathur/setup-php@2.6.0
      with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
          ini-values: post_max_size=256M, phar.readonly=0
          tools: php-cs-fixer, phpunit, composer:v2
